fun main(args: Array<String>) {

    var numbers = listOf(1, 2, 3, -2, 5, -6)
    val srez = numbers.subList(1, numbers.size)
    println(numbers[0])
    println(numbers.first())
    println(numbers.last())
    println("index: ${numbers.indexOf(2)}")
    println("last index: ${numbers.lastIndexOf(2)}")
    println(srez)
    println(numbers.contains(2))
    println(2 in numbers)
    println(numbers.indices)
    println(numbers.asReversed())
    println(numbers.distinct())
    var res = numbers.drop(2)
    println(res)
    res = numbers.dropLast(2)
    println(res)
    res = numbers.dropWhile { it < 3 }
    println(res)
    println(numbers.chunked(numbers.size / 2))
    println(numbers.sorted())
    println(numbers.sortedBy { it % 2 == 0 })
    val names = listOf("kim", "julia", "jim", "hala")
    var numbers2 = mutableListOf(1, 5, 4, 9)
    numbers2.add(2, 100500)
    println(numbers2)
    numbers2.reverse()
    println(numbers2)
    numbers2.replaceAll{ x -> x*2}
    println(numbers2)
    println(numbers2.filterNot { it%3 == 0 })
    var out = numbers.groupBy { it < 5 }
    println("out: ${out[true]}")
    println("out: ${out[false]}")
    println(out.keys)
    println(out.values)
    println(numbers.partition { it < 5 })
    numbers2.shuffle()
    println(numbers2)
}